# **Penting**
- Jangan menambahkan import libary atau function apa pun, selain yang sudah tersedia pada cell code atau yang diperbolehkan.
- Misal, Anda ingin membangun lebih dari satu model selain decision tree, yang mana itu diperbolehkan dalam instruksi, maka diperbolehkan untuk menambahkan beberapa code selain bagian yang rumpang.
- Jangan mengubah atau menambahkan cell text yang sudah disediakan, Anda hanya perlu mengerjakan cell code yang sudah disediakan.
- Ingat, tugas Anda hanyalah melengkapi code yang rumpang pada bagian yang sudah ditandai "________" saja.
- Pastikan seluruh kriteria memiliki output yang sesuai, karena jika tidak ada output dianggap tidak selesai.
- Misal, Anda menggunakan df = df.dropna() silakan gunakan df.isnull().sum() sebagai tanda sudah berhasil. Silakan sesuaikan seluruh output dengan perintah yang sudah disediakan.
- Pastikan juga output yang dihasilkan sesuai dengan output yang diharapkan (expected output). Sehingga Anda dapat mereview sendiri terlebih dahulu output dari cell code yang dijalankan.
- Pastikan Anda melakukan Run All sebelum mengirimkan submission untuk memastikan seluruh cell berjalan dengan baik.
- Pastikan Anda menggunakan variabel df dari awal sampai akhir dan tidak diperbolehkan mengganti nama variabel tersebut.
- Pastikan Anda mengerjakan sesuai section yang sudah diberikan tanpa mengubah judul atau header yang disediakan.

# **1. Import Library**
Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import classification_report
import joblib

# **2. Memuat Dataset dari Hasil Clustering**
Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [2]:
# Gunakan dataset hasil clustering yang memiliki fitur Target
# Silakan gunakan dataset data_clustering jika tidak menerapkan Interpretasi Hasil Clustering [Advanced]
# Silakan gunakan dataset data_clustering_inverse jika menerapkan Interpretasi Hasil Clustering [Advanced]

### MULAI CODE ###

df = pd.read_csv("data_clustering_inverse.csv")

### SELESAI CODE ###

In [3]:
# Tampilkan 5 baris pertama dengan function head

### MULAI CODE ###

df.head()

### SELESAI CODE ###

,TransactionAmount,TransactionType,Location,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,AgeGroup,Target,Target.1
0,14.09,Debit,San Diego,ATM,70.0,Doctor,81.0,1.0,5112.21,Senior,1,1
1,376.24,Debit,Houston,ATM,68.0,Doctor,141.0,1.0,13758.91,Senior,0,0
2,126.29,Debit,Mesa,Online,19.0,Student,56.0,1.0,1122.35,Young,2,2
3,184.50,Debit,Raleigh,Online,26.0,Student,25.0,1.0,8569.06,Young,0,0
4,92.15,Debit,Oklahoma City,ATM,18.0,Student,172.0,1.0,781.68,Young,2,2

## **(OPSIONAL) Feature Encoding: One Hot Encoding**
Langkah ini **HANYA** dilakukan saat Anda menggunakan **data hasil Inverse** untuk memenuhi kriteria Advanced pada latihan sebelumnya.

In [4]:
### MULAI CODE OPSIONAL ###

categorical_cols = list(df.select_dtypes(include=['object']).columns)

# Gunakan 'pd.get_dummies' untuk melakukan OneHotEncoding
df_encoded = pd.get_dummies(
    df,
    columns = categorical_cols,
    drop_first = True
)

# Tampilkan 5 baris pertama untuk memverifikasi hasilnya
df_encoded.head()

### SELESEI CODE OPSIONAL ###

,TransactionAmount,CustomerAge,TransactionDuration,LoginAttempts,AccountBalance,Target,Target.1,TransactionType_Debit,Location_Atlanta,Location_Austin,...,Location_Tucson,Location_Virginia Beach,Location_Washington,Channel_Branch,Channel_Online,CustomerOccupation_Engineer,CustomerOccupation_Retired,CustomerOccupation_Student,AgeGroup_Senior,AgeGroup_Young
0,14.09,70.0,81.0,1.0,5112.21,1,1,True,False,False,...,False,False,False,False,False,False,False,False,True,False
1,376.24,68.0,141.0,1.0,13758.91,0,0,True,False,False,...,False,False,False,False,False,False,False,False,True,False
2,126.29,19.0,56.0,1.0,1122.35,2,2,True,False,False,...,False,False,False,False,True,False,False,True,False,True
3,184.50,26.0,25.0,1.0,8569.06,0,0,True,False,False,...,False,False,False,False,True,False,False,True,False,True
4,92.15,18.0,172.0,1.0,781.68,2,2,True,False,False,...,False,False,False,False,False,False,False,True,False,True

# **3. Data Splitting**
Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [19]:
# Menggunakan train_test_split() untuk melakukan pembagian dataset.

### MULAI CODE ###

# Buat 'X' dengan menghapus 'Target' dari 'df_encoded' dan gunakan 'axis=1' untuk menandakan drop kolom.
X = df_encoded.drop('Target', axis=1)

# Buat 'y' dengan HANYA memilih kolom 'Target'.
y = df_encoded['Target']

# Panggil fungsi untuk membagi data.
#  - Gunakan 'stratify=y' agar proporsi kelas di train/test set sama.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42,
    stratify = y
)

### SELESAI CODE ###

print("Jumlah data total: ",len(X))
print("Jumlah data latih: ",len(X_train))
print("Jumlah data test: ",len(X_test))

Jumlah data total:  1945
Jumlah data latih:  1556
Jumlah data test:  389

# **4. Membangun Model Klasifikasi**
Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Menggunakan algoritma klasifikasi yaitu Decision Tree.
2. Latih model menggunakan data yang sudah dipisah.

In [17]:
# Implementasi DecisionTreeClassifier

### MULAI CODE ###

# Buat instance algorithm.
dt = DecisionTreeClassifier(
    random_state = 42,
    max_depth = 10,
    min_samples_split = 2,
    min_samples_leaf = 1
)

# Latih model dengan data training.
dt.fit(X_train, y_train)

# Simpan model dalam format pickle menggunakan joblib
joblib.dump(dt, 'model_decision_tree.pkl')

### SELESAI CODE ###

print("Model Decision Tree berhasil dilatih dan disimpan sebagai 'model_decision_tree.pkl'")

Model Decision Tree berhasil dilatih dan disimpan sebagai 'model_decision_tree.pkl'

In [18]:
# Prediksi dan evaluasi pada data testing.

### MULAI CODE ###

y_pred = dt.predict(X_test)
print("Classification Report:")
print(classification_report(y_test, y_pred))

### SELESAI CODE ###

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       118
           1       1.00      1.00      1.00       138
           2       1.00      1.00      1.00       133

    accuracy                           1.00       389
   macro avg       1.00      1.00      1.00       389
weighted avg       1.00      1.00      1.00       389

# **5. Memenuhi Kriteria Skilled dan Advanced dalam Membangun Model Klasifikasi**

**Biarkan kosong jika tidak menerapkan kriteria skilled atau advanced**

In [14]:
# Implementasi RandomForestClassifier

### MULAI CODE ###

# Buat model dengan RandomForestClassifier
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    max_depth=10,
    min_samples_split=2,
    min_samples_leaf=1
)

# Latih model pada data training
rf.fit(X_train, y_train)

# Simpan model dengan joblib
joblib.dump(rf, 'model_random_forest.pkl')

### SELESAI CODE ###

print("Model Random Forest berhasil dilatih dan disimpan sebagai 'model_random_forest.pkl'")

Model Random Forest berhasil dilatih dan disimpan sebagai 'model_random_forest.pkl'

In [15]:
# Prediksi dan evaluasi RandomForest

### MULAI CODE ###

# Prediksi dengan RandomForest
y_pred_rf = rf.predict(X_test)

print("Decision Tree Classification Report:")
print("="*50)
y_pred_dt = dt.predict(X_test)
print(classification_report(y_test, y_pred_dt))

print("\nRandom Forest Classification Report:")
print("="*50)
print(classification_report(y_test, y_pred_rf))

# Bandingkan accuracy
from sklearn.metrics import accuracy_score
dt_accuracy = accuracy_score(y_test, y_pred_dt)
rf_accuracy = accuracy_score(y_test, y_pred_rf)

print(f"\nComparison of Model Accuracy:")
print(f"Decision Tree Accuracy: {dt_accuracy:.4f}")
print(f"Random Forest Accuracy: {rf_accuracy:.4f}")

### SELESAI CODE ###

Decision Tree Classification Report:
==================================================
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       118
           1       1.00      1.00      1.00       138
           2       1.00      1.00      1.00       133

    accuracy                           1.00       389
   macro avg       1.00      1.00      1.00       389
weighted avg       1.00      1.00      1.00       389


Random Forest Classification Report:
==================================================
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       118
           1       1.00      1.00      1.00       138
           2       1.00      1.00      1.00       133

    accuracy                           1.00       389
   macro avg       1.00      1.00      1.00       389
weighted avg       1.00      1.00      1.00       389


Comparison of Model Accuracy:
Decision Tree Accuracy: 1.0000
Random Forest Accuracy: 1.0000

In [16]:
# Implementasi GridSearchCV untuk model terbaik berdasarkan evaluasi sebelumnya

### MULAI CODE ###

# Pilih model terbaik (biasanya Random Forest atau Decision Tree)
# Kita akan menggunakan Random Forest untuk hyperparameter tuning

# Parameter grid untuk Random Forest
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [5, 10, 15, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Implementasi GridSearchCV
grid_search = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_grid=param_grid,
    cv=3,  # 3-fold cross validation
    scoring='accuracy',
    n_jobs=-1  # Gunakan semua CPU cores
)

### SELESAI CODE ###

Hyperparameter Tuning Model

Pilih salah satu algoritma yang ingin Anda tuning

In [11]:
# Latih GridSearchCV dan tampilkan hasil

### MULAI CODE ###

print("Memulai hyperparameter tuning dengan GridSearchCV...")
print("Ini mungkin membutuhkan waktu beberapa menit...")

# Latih GridSearchCV
grid_search.fit(X_train, y_train)

# Tampilkan parameter terbaik
print("Parameter terbaik yang ditemukan:")
print(grid_search.best_params_)

print(f"\nCross-validation score terbaik: {grid_search.best_score_:.4f}")

# Model terbaik
best_model = grid_search.best_estimator_

# Simpan model terbaik
joblib.dump(best_model, 'best_model_tuned.pkl')

print("\nModel terbaik berhasil disimpan sebagai 'best_model_tuned.pkl'")

### SELESAI CODE ###

Memulai hyperparameter tuning dengan GridSearchCV...
Ini mungkin membutuhkan waktu beberapa menit...

/usr/local/python/3.12.1/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Parameter terbaik yang ditemukan:
{'max_depth': 5, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}

Cross-validation score terbaik: 1.0000

Model terbaik berhasil disimpan sebagai 'best_model_tuned.pkl'

In [12]:
# Evaluasi model yang sudah di-tuning

### MULAI CODE ###

# Prediksi dengan model yang sudah di-tuning
y_pred_tuned = best_model.predict(X_test)

print("Tuned Model Classification Report:")
print("="*50)
print(classification_report(y_test, y_pred_tuned))

# Bandingkan semua model
tuned_accuracy = accuracy_score(y_test, y_pred_tuned)

print(f"\nFinal Model Comparison:")
print("="*50)
print(f"Decision Tree Accuracy: {dt_accuracy:.4f}")
print(f"Random Forest Accuracy: {rf_accuracy:.4f}")
print(f"Tuned Model Accuracy: {tuned_accuracy:.4f}")

# Tentukan model terbaik
models = {
    'Decision Tree': dt_accuracy,
    'Random Forest': rf_accuracy,
    'Tuned Model': tuned_accuracy
}

best_model_name = max(models, key=models.get)
print(f"\nModel terbaik: {best_model_name} dengan accuracy: {models[best_model_name]:.4f}")

### SELESAI CODE ###

Tuned Model Classification Report:
==================================================
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       118
           1       1.00      1.00      1.00       138
           2       1.00      1.00      1.00       133

    accuracy                           1.00       389
   macro avg       1.00      1.00      1.00       389
weighted avg       1.00      1.00      1.00       389


Final Model Comparison:
==================================================
Decision Tree Accuracy: 1.0000
Random Forest Accuracy: 1.0000
Tuned Model Accuracy: 1.0000

Model terbaik: Decision Tree dengan accuracy: 1.0000

In [13]:
# Summary dan kesimpulan

### MULAI CODE ###

print("SUMMARY - HASIL KLASIFIKASI")
print("="*60)
print("\n1. Dataset Information:")
print(f"   - Total samples: {len(X)}")
print(f"   - Training samples: {len(X_train)}")
print(f"   - Testing samples: {len(X_test)}")
print(f"   - Features: {X.shape[1]}")
print(f"   - Classes: {len(y.unique())}")

print(f"\n2. Model Performance:")
print(f"   - Decision Tree: {dt_accuracy:.4f}")
print(f"   - Random Forest: {rf_accuracy:.4f}")
print(f"   - Tuned Model: {tuned_accuracy:.4f}")

print(f"\n3. Best Model: {best_model_name}")
print(f"   - Best Parameters: {grid_search.best_params_}")
print(f"   - Cross-validation Score: {grid_search.best_score_:.4f}")
print(f"   - Test Set Accuracy: {models[best_model_name]:.4f}")

print(f"\n4. Saved Models:")
print(f"   - model_decision_tree.pkl")
print(f"   - model_random_forest.pkl") 
print(f"   - best_model_tuned.pkl")

print("\n5. Kesimpulan:")
print(f"   Model klasifikasi berhasil dibangun untuk memprediksi cluster")
print(f"   berdasarkan fitur-fitur yang telah di-encode. Model terbaik")
print(f"   adalah {best_model_name} dengan akurasi {models[best_model_name]:.1%}.")

### SELESAI CODE ###

SUMMARY - HASIL KLASIFIKASI
============================================================

1. Dataset Information:
   - Total samples: 1945
   - Training samples: 1556
   - Testing samples: 389
   - Features: 56
   - Classes: 3

2. Model Performance:
   - Decision Tree: 1.0000
   - Random Forest: 1.0000
   - Tuned Model: 1.0000

3. Best Model: Decision Tree
   - Best Parameters: {'max_depth': 5, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
   - Cross-validation Score: 1.0000
   - Test Set Accuracy: 1.0000

4. Saved Models:
   - model_decision_tree.pkl
   - model_random_forest.pkl
   - best_model_tuned.pkl

5. Kesimpulan:
   Model klasifikasi berhasil dibangun untuk memprediksi cluster
   berdasarkan fitur-fitur yang telah di-encode. Model terbaik
   adalah Decision Tree dengan akurasi 100.0%.

End of Code